Feature/#16 add calculate winner function
Fanta335/Connect4-GroupH pull request #38
Opened 2021-11-08 13:54 UTC by y0uk1

勝者を判定して返す関数を実装しました。

close #16

2021-11-09 04:44 UTC, Fanta335 commented on src/pages/GameDisplayPage.js
> + * @param {string[]} squares - 盤面を表す配列
`squares`は盤面を表すので、二次元配列です。
型は、`string[][]`で表記できます。

2021-11-09 05:40 UTC, Fanta335 requested changes
JSDocコメントなどとても読みやすいです！
計算量の改善など、ぜひ試してみてください。

また、この勝敗判定ロジックなのですが、ほかのファイルに分けたほうがいいかもしれません。
`utils`などのディレクトリの中に計算ロジックを置いておけば、「見た目」を表すコンポーネントと「ロジック」をうまく分離できると思います。
```
こんな感じです

src/
  components/
  ....
  utils/
    calculateWinner.js
```

コンポーネント側はロジックの中身には興味が無いので、そのほうがいい感じですよね？

2021-11-09 05:40 UTC, Fanta335 commented on src/pages/GameDisplayPage.js
> + * @param {string} user - userの名前('X', 'O' など)
userの型定義について、さらに限定することもできます。
TypeScript などではリテラル型（[参考](https://typescript-jp.gitbook.io/deep-dive/type-system/literal-types)）と呼ぶのですが、入る値を列挙することができます。当然JSなので型チェックはありませんが。。。
```suggestion
 * @param {'X'|'O'} user - userの名前('X', 'O' など)
```

2021-11-09 05:40 UTC, Fanta335 commented on src/pages/GameDisplayPage.js
> + * @param {string[]} arr - 盤面を表す配列
上のと同様に、二次元配列を示したほうが親切ですね！
```suggestion
 * @param {string[][]} arr - 盤面を表す二次元配列
```

2021-11-09 05:40 UTC, Fanta335 commented on src/pages/GameDisplayPage.js
> +function isConnectedN(arr, user, n) {
ロジックは完璧です！
ただ、より計算量を考慮することもできます。
現在のコードは、プレイヤーがプレイをするたびにその時点での盤面全体を走査しています。しかし実際は、プレイされた位置を中心に調べれば判定はできるはずです。
入力値を工夫して走査の範囲を最適化してみてください！

2021-11-09 13:25 UTC, y0uk1 commented
関数を`src/utils/calculateWinner.js`に移動しました。
また、置かれた石の座標を中心に探索するようにアルゴリズムを変更しました。

close #38

2021-11-09 14:16 UTC, y0uk1 commented
関数をsrc/utils/calculateWinner.jsに移動しました。
また、置かれた石の座標を中心に探索するようにアルゴリズムを変更しました。

close #16

2021-11-10 04:43 UTC, Fanta335 approved these changes

2021-11-10 04:44 UTC, merged