Feature/#24 add time control function
Fanta335/Connect4-GroupH pull request #76
Opened 2021-11-25 12:58 UTC by y0uk1

持ち時間機能を追加しました。
- ホーム画面から遷移した直後にカウントダウンが始まらないように、START NEW GAMEを押してからゲームを開始するように変更しました
- 設定画面から持ち時間を変更することができます
- 先に持ち時間が無くなった方が負けです

タイマーを止めないまま、左上のボタンでページ遷移すると以下のエラーが出ます。左上のボタンにonClickでタイマーの停止を発動させたいですが、左上のボタンが前ページで共通化されているので、一旦保留にしています。

```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at GameDisplayPage (http://localhost:3000/main.dd79cc315d45e3846b7b.hot-update.js:73:97)
```

close #24

2021-11-26 06:07 UTC, Fanta335 requested changes
再レンダリングを抑制するほうの修正だけしてみてください。
カスタムフックはできたらで大丈夫です！

2021-11-26 06:07 UTC, Fanta335 commented on src/pages/GameDisplayPage.js
> +  }, []);
リファクタ案としてですが、ここの処理を「カスタムフック」として分離することもできます。（参考：https://ja.reactjs.org/docs/hooks-custom.html ）
今回のコードで使われている変数名を使って説明しますと、以下のようなカスタムフック（関数、APIとして考えて大丈夫です）が考えられます。
入力：`timeControl`
出力：`[count1, startTimer1, stopTimer1]`

この処理を`src/hooks/useTimer.js`などとして分離すると、`src/pages/GameDisplayPage.js`では以下のように使用できます。

```javascript
const GameDisplayPage = (props) => {
  // ...
  const [count1, startTimer1, stopTimer1] = useTimer(timeControl);
  const [count2, startTimer2, stopTimer2] = useTimer(timeControl);
  
  const controlTimer = (player1IsNext) => {
    if (player1IsNext) {
      startTimer1();
      stopTimer2();
    } else {
      stopTimer1();
      startTimer2();
    }
  };
  // ...
}
```

`useTimer.js`の具体的な実装についてはおまかせしますが、基本的にはOkumaさんのコードを移動させる感じでいけると思います！

2021-11-26 06:07 UTC, Fanta335 commented on src/pages/GameDisplayPage.js
> +      <Board board={currentBoard} onClick={canStartGame ? handleClick : null} />
React devtoolsで確認できるのですが、タイマー機能を実装したことにより、大量のレンダリングが発生しています。
具体的には、タイマーのカウントが10 ms減るごとに一回レンダリングしているので、CPU使用率がすごいことになりますｗ

僕の方でためした簡単な解決策としては、`startTimer`内のsetIntervalの引数を10 -> 1000にするとレンダリングの数は100分の1になるのでパフォーマンスはかなりましになりました。

パフォーマンスの改善方法として、useCallbackやmemo, useMemoがありますが、今回の場合このまま使うのは難しそうですね。クリックイベントの設計から考え直す必要がある（＆いい案がうかばない）のでこっちはスルーしていいと思います。

Reactの再レンダリングの仕組みについてはちょっと知っておいたほうがいいので、興味があれば調べてみてください。（参考：https://zenn.dev/b1essk/articles/react-re-rendering ）

2021-11-26 06:31 UTC, y0uk1 commented on src/pages/GameDisplayPage.js
> +      <Board board={currentBoard} onClick={canStartGame ? handleClick : null} />
最初は10->1000にしていたんですが、1秒経たないうちに石を置かれると、秒数が減らないので、1/100秒にしてました。一旦そこはあきらめて、1秒単位に変更します。

2021-11-26 06:41 UTC, Fanta335 commented on src/pages/GameDisplayPage.js
> +      <Board board={currentBoard} onClick={canStartGame ? handleClick : null} />
なるほど・・・
それか、持ち時間をターン毎にリセットするのはどうですか？
5秒で設定したら、お互いに5秒以内に打たなければならないとか。

2021-11-26 07:11 UTC, y0uk1 commented on src/pages/GameDisplayPage.js
> +      <Board board={currentBoard} onClick={canStartGame ? handleClick : null} />
実際考えながらプレイして1秒以内に置かれることはレアケースだと思うので、10->1000に変更する方針で行きたいと思います！

2021-11-26 16:38 UTC, y0uk1 commented
timer機能のcustom hookへの抽出と1/100秒単位から1秒単位への変更が完了しました。

2021-11-27 00:24 UTC, Fanta335 approved these changes

2021-11-27 00:24 UTC, merged