#64 CPU対戦の際、先攻後攻をランダムに決定する機能を追加
Fanta335/Connect4-GroupH pull request #77
Opened 2021-11-26 10:42 UTC by YuyaNakamura0139

CPU対戦を実装する前に先攻後攻をランダムに決定する機能を追加しました。

createNewBoard.jsで初期盤面を生成する際に、生成した乱数を2で割った時の余りの場合分けで手番を決定します。
プレイヤーが後攻の場合は、CPUが先に一手ランダムに打った状態にして初期盤面をレンダリングさせます。

レビューの方よろしくお願いいたします！

2021-11-26 11:28 UTC, Fanta335 requested changes

2021-11-26 11:28 UTC, Fanta335 commented on src/utils/createNewBoard.js
> +    if (decideOrder() == false) {
```suggestion
  if (gameMode === "cpu") {
    if (decideOrder() === false) {
```

ご存知かもしれませんが、JavaScriptでは等価演算子として、`===`と`==`があります。
厳密等価演算子（===）は型まで比較して同じかどうかチェックするので、基本的に同じ値かどうかチェックしたいときはイコール3つのほうを使うようにしましょう！！
参考：https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Strict_equality

余談ですが、===の使用を強制するESLintのルールもありますｗ

2021-11-26 11:28 UTC, Fanta335 commented on src/utils/decideOrder.js
> +  if (randomNumber % 2 == 0) return true;
```suggestion
  if (randomNumber % 2 === 0) return true;
```

2021-11-26 11:28 UTC, Fanta335 commented on src/utils/decideOrder.js
> +function decideOrder() {
「プレイヤーが先攻か？」に対して真偽値を返す関数なので、decideOrderよりもisPlayerFirstとかはどうでしょうか？
真偽値を返す関数のネーミングについて調べてみると面白いですよ！

2021-11-26 11:55 UTC, YuyaNakamura0139 commented on src/utils/decideOrder.js
> +function decideOrder() {
真偽値を返す関数の場合isやexistsなどを用いるのですね！
関数名にもっとこだわっていきます！

2021-11-26 11:56 UTC, YuyaNakamura0139 commented on src/utils/createNewBoard.js
> +    if (decideOrder() == false) {
すみません！意識して使えてなかったです、、
以後気をつけて厳密等価演算子使っていきます！

2021-11-26 12:16 UTC, Fanta335 requested changes

2021-11-26 12:16 UTC, Fanta335 commented on src/utils/isPlayerFirst.js
> +function isPlayrFirst() {
```suggestion
function isPlayerFirst() {
```
タイポです！

2021-11-26 14:28 UTC, YuyaNakamura0139 commented on src/utils/isPlayerFirst.js
> +function isPlayrFirst() {
失礼しました！すぐ修正します！

2021-11-27 00:26 UTC, Fanta335 approved these changes

2021-11-27 00:27 UTC, merged

2021-11-27 01:44 UTC, y0uk1 commented
close #64